version: '3'

services:
  elkjsmicroservice:
    build:
      context: ./ # Local
      dockerfile: Dockerfile_arm64
    #      context: https://github.com/elbosso/generator-microservices.git # Build from Github
    container_name: elkjsmicroservice
    hostname: elkjsmicroservice
#    ports:
#      - 7070:7070
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.elkjsmicroservice-http.entrypoints=http"
      - "traefik.http.routers.elkjsmicroservice-http.rule=Host(`elkjsmicroservice.pi-docker.lab`)"
      - "traefik.http.routers.elkjsmicroservice-http.middlewares=elkjsmicroservice-https"
      - "traefik.http.services.elkjsmicroservice-http.loadbalancer.server.port=7070"
      - "traefik.http.middlewares.elkjsmicroservice-https.redirectscheme.scheme=https"
      - "traefik.http.routers.elkjsmicroservice.entrypoints=https"
      - "traefik.http.routers.elkjsmicroservice.rule=Host(`elkjsmicroservice.pi-docker.lab`)"
      - "traefik.http.routers.elkjsmicroservice.tls=true"
      - "traefik.docker.network=pi_traefik_proxy"
    networks:
      - traefik_proxy

networks:
  traefik_proxy:
    external:
      name: pi_traefik_proxy
